/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Sun May 10 17:54:44 2015
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_LCD_ID_CHANNEL     1


#endif //_CUST_AUXADC_TOOL_H


