/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Tue May  9 12:51:22 2023
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


